/* 자동 생성: PDF 페이지 제목 (scripts: pymupdf largest-font heuristic) */
export const BT_TITLES: string[] = [
  "Algorithm",
  "백트래킹과상태공간트리에대한이해",
  "지난이야기",
  "상태 공간 트리",
  "상태 공간 트리",
  "상태 공간 트리",
  "상태 공간 트리",
  "즉, DP와는 다른 Smart Brute-Force 기법으로 볼 수 있음",
  "1. 백트래킹과 상태 공간 트리",
  "유망 함수",
  "유망 함수의 건전성",
  "예제 – 미로 문제",
  "예제 – 미로 문제",
  "예제 – 미로 문제",
  "예제 – 미로 문제",
  "예제 – 미로 문제",
  "N-Queens 문제",
  "N-Queens 문제",
  "N-Queens 문제",
  "N-Queens 문제",
  "N-Queens 문제",
  "그래프 색칠 문제",
  "그래프 색칠 문제",
  "그래프 색칠 문제",
  "그래프 색칠 문제",
  "그래프 색칠 문제",
  "그래프 색칠 문제",
  "부분 집합의 합 문제",
  "부분 집합의 합 문제",
  "부분 집합의 합 문제",
  "부분 집합의 합 문제",
  "부분 집합의 합 문제",
  "0/1 배낭 문제",
  "0/1 배낭 문제",
  "0/1 배낭 문제",
  "0/1 배낭 문제",
  "0/1 배낭 문제",
  "N-Queens 문제"
];

export const CN_TITLES: string[] = [
  "Computer Network",
  "Chapter 5: Network Layer",
  "Introduction",
  "Network",
  "router control plane",
  "Logically centralized control plane",
  "routing protocols",
  "Routing",
  "Graph abstraction of the network",
  "Routing algorithm classification",
  "routing protocols",
  "A link",
  "Dijsktra",
  "Dijkstra",
  "Dijkstra",
  "Dijkstra",
  "routing protocols",
  "Distance vector algorithm",
  "Distance vector algorithm",
  "Distance vector algorithm",
  "Dy(z), c(x,z) + Dz(z)}",
  "Dy(z), c(x,z) + Dz(z)}",
  "Distance vector: link cost changes",
  "Distance vector: link cost changes",
  "Comparison of LS and DV algorithms",
  "intra",
  "Making routing scalable",
  "Internet approach to scalable routing",
  "Interconnected",
  "Inter",
  "Intra",
  "OSPF (Open Shortest Path First)",
  "routing among the ISPs: BGP",
  "Internet inter",
  "eBGP, iBGP connections",
  "BGP basics",
  "BGP path advertisement",
  "BGP path advertisement",
  "BGP, OSPF, forwarding table entries",
  "BGP, OSPF, forwarding table entries",
  "BGP route selection",
  "Hot Potato Routing",
  "BGP: achieving policy via advertisements",
  "BGP: achieving policy via advertisements",
  "Why different Intra",
  "ICMP: The Internet Control Message",
  "ICMP: internet control message protocol",
  "Traceroute and ICMP",
  "Network management and SNMP",
  "What is network management?",
  "Infrastructure for network management",
  "Chapter 5: summary"
];
